"""Competition-only PostgreSQL adapter; no SQLite production fallback."""
from __future__ import annotations

import os
import re

import psycopg2
from psycopg2.extras import DictCursor


class Connection:
    is_postgres = True
    row_factory = None

    def __init__(self):
        dsn = os.environ["DATABASE_URL"]
        self.raw = psycopg2.connect(dsn, connect_timeout=5,
                                   options="-c search_path=competition -c statement_timeout=15000 -c lock_timeout=3000")
        if self.raw.info.dbname != "website_business":
            self.raw.close()
            raise RuntimeError("应用只能连接平台的 website_business 数据库")

    def execute(self, statement, parameters=()):
        query = statement.strip().rstrip(";")
        query = re.sub(r"INTEGER\s+PRIMARY KEY\s+AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", query, flags=re.I)
        query = re.sub(r"\bINTEGER\b", "BIGINT", query, flags=re.I)
        query = re.sub(r"\bREAL\b", "DOUBLE PRECISION", query, flags=re.I)
        query = query.replace("%", "%%").replace("?", "%s")
        cursor = self.raw.cursor(cursor_factory=DictCursor)
        cursor.execute(query, parameters)
        return cursor

    def executescript(self, script):
        for statement in script.split(";"):
            if statement.strip():
                # PostgreSQL checks table ownership even for CREATE INDEX IF
                # NOT EXISTS. Existing platform-owned indexes need no DDL.
                index = re.match(r"CREATE INDEX IF NOT EXISTS ([a-z_][a-z0-9_]*)\b", statement.strip(), flags=re.I)
                if index:
                    existing = self.execute("SELECT to_regclass(?)", ("competition." + index[1],)).fetchone()
                    if existing[0] is not None:
                        continue
                self.execute(statement)

    def commit(self):
        self.raw.commit()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        try:
            self.raw.rollback() if exc_type else self.raw.commit()
        finally:
            self.raw.close()


def connect_database(path, schema, timeout=5):
    if schema != "competition":
        raise RuntimeError("应用不能访问其他数据区域")
    return Connection()
